/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab1: typeof import('./src/components/Tab1.vue')['default']
    Tab2: typeof import('./src/components/Tab2.vue')['default']
    Tab3: typeof import('./src/components/Tab3.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    UserPosts: typeof import('./src/components/UserPosts.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
